apiVersion: v1
kind: Service
metadata:
  name: my-simple-app-service
spec:
  selector:
    app: my-simple-app
  ports:
    - protocol: TCP
      port: 80       # Port the service is available on within the cluster
      targetPort: 5000 # Port your container is running on
  type: LoadBalancer # Or NodePort for simpler local testing, ClusterIP if not exposing externally initially 
  